In [2]:
import pandas as pd

# Load the data from the raw URL
url = "https://raw.githubusercontent.com/falsefoobar/CS381/main/depression_dataset.txt"

# Try reading as CSV; if tab-separated, change to sep="\t"
df = pd.read_csv(url)

# Show dataset shape
print("Shape of dataset:", df.shape)

# Show column names
print("\nColumns:", df.columns.tolist())

# Show the first few rows
print("\nFirst 5 rows:")
print(df.head())

# Describe numeric and categorical data
print("\nSummary statistics:")
print(df.describe(include='all'))

# Check missing values
print("\nMissing values:")
print(df.isnull().sum())

Shape of dataset: (27900, 18)

Columns: ['2', 'Male', '33.0', 'Visakhapatnam', 'Student', '5.0', '0.0', '8.97', '2.0', '0.0.1', "'5-6 hours'", 'Healthy', 'B.Pharm', 'Yes', '3.0', '1.0', 'No', '1']

First 5 rows:
    2    Male  33.0 Visakhapatnam  Student  5.0  0.0  8.97  2.0  0.0.1  \
0   8  Female  24.0     Bangalore  Student  2.0  0.0  5.90  5.0    0.0
1  26    Male  31.0      Srinagar  Student  3.0  0.0  7.03  5.0    0.0
2  30  Female  28.0      Varanasi  Student  3.0  0.0  5.59  2.0    0.0
3  32  Female  25.0        Jaipur  Student  4.0  0.0  8.13  3.0    0.0
4  33    Male  29.0          Pune  Student  2.0  0.0  5.70  3.0    0.0

           '5-6 hours'   Healthy B.Pharm  Yes  3.0  1.0   No  1
0          '5-6 hours'  Moderate     BSc   No  3.0  2.0  Yes  0
1  'Less than 5 hours'   Healthy      BA   No  9.0  1.0  Yes  0
2          '7-8 hours'  Moderate     BCA  Yes  4.0  5.0  Yes  1
3          '5-6 hours'  Moderate  M.Tech  Yes  1.0  1.0   No  0
4  'Less than 5 hours'   Healthy     PhD   No  4.0  1.0   No  0

Summary statistics:
                    2   Male          33.0 Visakhapatnam  Student  \
count    27900.000000  27900  27900.000000         27900    27900
unique            NaN      2           NaN            52       14
top               NaN   Male           NaN        Kalyan  Student
freq              NaN  15546           NaN          1570    27869
mean     70444.674158    NaN     25.822043           NaN      NaN
std      40639.715432    NaN      4.905587           NaN      NaN
min          8.000000    NaN     18.000000           NaN      NaN
25%      35044.250000    NaN     21.000000           NaN      NaN
50%      70689.000000    NaN     25.000000           NaN      NaN
75%     105820.250000    NaN     30.000000           NaN      NaN
max     140699.000000    NaN     59.000000           NaN      NaN

                 5.0           0.0          8.97           2.0         0.0.1  \
count   27900.000000  27900.000000  27900.000000  27900.000000  27900.000000
unique           NaN           NaN           NaN           NaN           NaN
top              NaN           NaN           NaN           NaN           NaN
freq             NaN           NaN           NaN           NaN           NaN
mean        3.141147      0.000430      7.656057      2.943871      0.000681
std         1.381445      0.043993      1.470713      1.361161      0.044395
min         0.000000      0.000000      0.000000      0.000000      0.000000
25%         2.000000      0.000000      6.290000      2.000000      0.000000
50%         3.000000      0.000000      7.770000      3.000000      0.000000
75%         4.000000      0.000000      8.920000      4.000000      0.000000
max         5.000000      5.000000     10.000000      5.000000      4.000000

                '5-6 hours'    Healthy     B.Pharm    Yes           3.0  \
count                 27900      27900       27900  27900  27900.000000
unique                    5          4          28      2           NaN
top     'Less than 5 hours'  Unhealthy  'Class 12'    Yes           NaN
freq                   8310      10317        6080  17655           NaN
mean                    NaN        NaN         NaN    NaN      7.157133
std                     NaN        NaN         NaN    NaN      3.707625
min                     NaN        NaN         NaN    NaN      0.000000
25%                     NaN        NaN         NaN    NaN      4.000000
50%                     NaN        NaN         NaN    NaN      8.000000
75%                     NaN        NaN         NaN    NaN     10.000000
max                     NaN        NaN         NaN    NaN     12.000000

          1.0     No             1
count   27900  27900  27900.000000
unique      6      2           NaN
top       5.0     No           NaN
freq     6715  14397           NaN
mean      NaN    NaN      0.585484
std       NaN    NaN      0.492647
min       NaN    NaN      0.000000
25%       NaN    NaN      0.000000
50%       NaN    NaN      1.000000
75%       NaN    NaN      1.000000
max       NaN    NaN      1.000000

Missing values:
2                0
Male             0
33.0             0
Visakhapatnam    0
Student          0
5.0              0
0.0              0
8.97             0
2.0              0
0.0.1            0
'5-6 hours'      0
Healthy          0
B.Pharm          0
Yes              0
3.0              0
1.0              0
No               0
1                0
dtype: int64

In [7]:
columns = [
    "id", "Gender", "Age", "City", "Profession", "Academic Pressure", "Work Pressure", "CGPA",
    "Study Satisfaction", "Job Satisfaction", "Sleep Duration", "Dietary Habits", "Degree",
    "Have you ever had suicidal thoughts ?", "Work/Study Hours", "Financial Stress",
    "Family History of Mental Illness", "Depression"
]
df.columns = columns

In [8]:
print(df.head())
print("\nNew column names:", df.columns.tolist())

   id  Gender   Age       City Profession  Academic Pressure  Work Pressure  \
0   8  Female  24.0  Bangalore    Student                2.0            0.0
1  26    Male  31.0   Srinagar    Student                3.0            0.0
2  30  Female  28.0   Varanasi    Student                3.0            0.0
3  32  Female  25.0     Jaipur    Student                4.0            0.0
4  33    Male  29.0       Pune    Student                2.0            0.0

   CGPA  Study Satisfaction  Job Satisfaction       Sleep Duration  \
0  5.90                 5.0               0.0          '5-6 hours'
1  7.03                 5.0               0.0  'Less than 5 hours'
2  5.59                 2.0               0.0          '7-8 hours'
3  8.13                 3.0               0.0          '5-6 hours'
4  5.70                 3.0               0.0  'Less than 5 hours'

  Dietary Habits  Degree Have you ever had suicidal thoughts ?  \
0       Moderate     BSc                                    No
1        Healthy      BA                                    No
2       Moderate     BCA                                   Yes
3       Moderate  M.Tech                                   Yes
4        Healthy     PhD                                    No

   Work/Study Hours Financial Stress Family History of Mental Illness  \
0               3.0              2.0                              Yes
1               9.0              1.0                              Yes
2               4.0              5.0                              Yes
3               1.0              1.0                               No
4               4.0              1.0                               No

   Depression
0           0
1           0
2           1
3           0
4           0

New column names: ['id', 'Gender', 'Age', 'City', 'Profession', 'Academic Pressure', 'Work Pressure', 'CGPA', 'Study Satisfaction', 'Job Satisfaction', 'Sleep Duration', 'Dietary Habits', 'Degree', 'Have you ever had suicidal thoughts ?', 'Work/Study Hours', 'Financial Stress', 'Family History of Mental Illness', 'Depression']

In [9]:
df.describe()

,id,Age,Academic Pressure,Work Pressure,CGPA,Study Satisfaction,Job Satisfaction,Work/Study Hours,Depression
count,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000,27900.000000
mean,70444.674158,25.822043,3.141147,0.000430,7.656057,2.943871,0.000681,7.157133,0.585484
std,40639.715432,4.905587,1.381445,0.043993,1.470713,1.361161,0.044395,3.707625,0.492647
min,8.000000,18.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,35044.250000,21.000000,2.000000,0.000000,6.290000,2.000000,0.000000,4.000000,0.000000
50%,70689.000000,25.000000,3.000000,0.000000,7.770000,3.000000,0.000000,8.000000,1.000000
75%,105820.250000,30.000000,4.000000,0.000000,8.920000,4.000000,0.000000,10.000000,1.000000
max,140699.000000,59.000000,5.000000,5.000000,10.000000,5.000000,4.000000,12.000000,1.000000